version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: blog
    environment:
      - JEKYLL_ENV=docker
      - BUNDLE_GEMFILE=/srv/jekyll/Gemfile
      - BUNDLE_JOBS=2
      - BUNDLE_PATH=/srv/jekyll/_bundle
    command: jekyll serve --force_polling --livereload --drafts
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
