apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: docker.pkg.github.com/taufek/blog/blog
          ports:
            - name: blog-port
              containerPort: 80
            - name: s-blog-port
              containerPort: 443
